### PR TITLE
Search fixes:

### PR DESCRIPTION
**Pull request by Alzigopri**
Fix case insensitive search
    Fix buffer overrun
    Fix backward search

### CODE REVIEW

**Comment by fenugrec** [comment]
Promising, but would be nice if it was split in at least 3 commits, with some additional explanations in the commits, in particular regarding the EndModal changes, the unrelated SSE2 changes, etc. As is, it's nearly impossible to review.

**Comment by Alzigopri** [comment]
Why do you bother about patches  to the project which hasn't been updated 2 years? It wouldn't be committed anyway   :-)

**Comment by fenugrec** [comment]
Because I, and others, may use it in our own fork !

**Comment by EUA** [comment]
I review the codes. I don't catch where I make a mistake. But if it works like that, okay. I am happy with.

**Pull request merged**
